import Link from "next/link";
import { ArrowRight, CalendarCheck2, Check, ShieldCheck, UserRoundCheck, WalletCards } from "lucide-react";

const steps = [
  ["Maak jezelf zichtbaar", "Bouw een profiel met je ervaring, specialisaties, talen en beschikbaarheid."],
  ["Kies opdrachten die passen", "Bekijk werk op basis van locatie, planning en het soort inzet dat jij zoekt."],
  ["Regel het professioneel", "Houd contact, afspraken, betalingen en facturen overzichtelijk bij."],
];

export default function ProfessionalInformationPage() {
  return <main className="overflow-hidden bg-[#fff8f5] text-[#172629]">
    <section className="relative bg-[#e76f51] px-5 py-8 text-[#172629] sm:px-8 lg:px-10 lg:py-12"><div className="mx-auto max-w-7xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#5d2c25] hover:text-[#172629]"><ArrowRight className="rotate-180" size={16} />Terug naar home</Link><div className="grid items-end gap-10 pb-12 pt-16 lg:grid-cols-[0.9fr_1.1fr] lg:pb-20 lg:pt-24"><div className="order-2 lg:order-1"><div className="relative max-w-md"><div className="absolute -inset-4 -rotate-3 bg-[#f7baaa]/70" /><div className="relative bg-[#fff1ec] p-7 sm:p-9"><ShieldCheck size={34} className="text-[#bd513c]" /><p className="mt-12 text-3xl font-bold leading-tight">Jouw vak. Jouw planning. Jouw keuze.</p><p className="mt-4 text-sm leading-6 text-[#5d4a46]">Laat opdrachtgevers zien waar jij goed in bent en neem werk aan dat bij je past.</p></div></div></div><div className="order-1 max-w-3xl lg:order-2"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#6d2d22]">Voor ZZP-beveiligers</p><h1 className="mt-5 text-5xl font-bold leading-[1.03] sm:text-6xl">Werk dat aansluit op jouw manier van werken.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#5d2c25]">SecurityMatch brengt je in contact met opdrachtgevers die jouw ervaring en beschikbaarheid nodig hebben.</p><div className="mt-9 flex flex-wrap gap-3"><Link className="inline-flex min-h-12 items-center gap-2 rounded-lg bg-[#172629] px-5 text-sm font-bold text-white hover:bg-[#304347]" href="/register?role=SECURITY_PROFESSIONAL">Maak je profiel <ArrowRight size={17} /></Link><Link className="inline-flex min-h-12 items-center gap-2 rounded-lg border border-[#7e392e]/40 px-5 text-sm font-bold hover:bg-white/20" href="#zo-werkt-het">Ontdek de werkwijze <ArrowRight size={17} /></Link></div></div></div></div></section>
    <section id="zo-werkt-het" className="px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 border-b border-[#efd5cc] pb-8 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#bd513c]">Jouw route</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Van profiel naar passende opdracht.</h2></div><p className="max-w-md text-sm leading-6 text-[#566267]">Een eenvoudige werkstroom die ruimte laat voor het echte werk.</p></div><div className="grid gap-5 pt-8 md:grid-cols-3">{steps.map(([title, text], index) => <article key={title} className="border-t-4 border-[#e76f51] bg-white p-6"><span className="text-sm font-bold text-[#bd513c]">0{index + 1}</span><h3 className="mt-8 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-[#566267]">{text}</p></article>)}</div></div></section>
    <section className="bg-white px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#bd513c]">Gebouwd rond jouw werk</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Meer grip, minder losse lijntjes.</h2><p className="mt-5 max-w-lg text-base leading-7 text-[#566267]">Je profiel, agenda en opdrachten werken samen. Zo kun je professioneel reageren zonder je vrijheid kwijt te raken.</p><Link className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#bd513c] underline underline-offset-4" href="/register?role=SECURITY_PROFESSIONAL">Aan de slag als beveiliger <ArrowRight size={17} /></Link></div><div className="grid gap-4 sm:grid-cols-2"><div className="border border-[#f0d9d1] bg-[#fff8f5] p-5"><CalendarCheck2 className="text-[#bd513c]" size={25} /><p className="mt-8 text-lg font-bold">Planning die meebeweegt</p></div><div className="border border-[#f0d9d1] bg-[#fff8f5] p-5"><WalletCards className="text-[#bd513c]" size={25} /><p className="mt-8 text-lg font-bold">Overzichtelijke betalingen</p></div><div className="border border-[#f0d9d1] bg-[#fff8f5] p-5"><UserRoundCheck className="text-[#bd513c]" size={25} /><p className="mt-8 text-lg font-bold">Een profiel op jouw naam</p></div><div className="border border-[#f0d9d1] bg-[#fff8f5] p-5"><Check className="text-[#bd513c]" size={25} /><p className="mt-8 text-lg font-bold">Afspraken duidelijk vastgelegd</p></div></div></div></section>
    <section className="px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto max-w-7xl border-l-4 border-[#08705f] bg-[#f1f6f3] p-7 sm:p-10"><div className="grid gap-8 md:grid-cols-[auto_1fr] md:items-start"><ShieldCheck className="text-[#08705f]" size={34} /><div><h2 className="text-2xl font-bold">Jouw gegevens blijven zorgvuldig behandeld.</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-[#566267]">Je bepaalt welke profielinformatie je deelt. Verificatiedocumenten zijn niet openbaar. Lees de <Link className="font-bold text-[#08705f] underline" href="/privacy">privacyverklaring</Link> en <Link className="font-bold text-[#08705f] underline" href="/verificatie">verificatie-informatie</Link>. Een probleem melden kan via <Link className="font-bold text-[#08705f] underline" href="/melden">Meld een probleem</Link>.</p></div></div></div></section>
    <section className="bg-[#172629] px-5 py-16 text-white sm:px-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#f7baaa]">Jouw volgende opdracht</p><h2 className="mt-3 text-3xl font-bold">Laat zien wat je kunt.</h2></div><Link className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg bg-[#f7baaa] px-5 text-sm font-bold text-[#172629] hover:bg-white" href="/register?role=SECURITY_PROFESSIONAL">Profiel maken <ArrowRight size={17} /></Link></div></section>
  </main>;
}
