import Link from "next/link";
import { ArrowRight, CalendarCheck2, ShieldCheck, WalletCards } from "lucide-react";
import { LegalPage, LegalSection } from "@/components/legal-page";

const points = [
  ["Maak je profiel compleet", "Laat zien welke ervaring, specialisaties, talen en beschikbaarheid bij jou passen."],
  ["Vind passend werk", "Bekijk opdrachten die aansluiten bij jouw expertise, locatie en planning."],
  ["Werk professioneel", "Communiceer duidelijk, houd afspraken bij en beheer betalingen en facturen op één plek."],
];

export default function ProfessionalInformationPage() {
  return <LegalPage eyebrow="Voor ZZP-beveiligers" title="Werk op jouw voorwaarden met een professioneel profiel." introduction="SecurityMatch brengt zelfstandige beveiligingsprofessionals en opdrachtgevers samen. Jij bepaalt welke opdrachten passen en houdt overzicht over je werk.">
    <LegalSection title="Zo werkt het"><div className="grid gap-4 sm:grid-cols-3">{points.map(([title, text], index) => <article key={title} className="border border-[#e6ded8] bg-white p-5"><span className="text-sm font-bold text-[#bd513c]">0{index + 1}</span><h3 className="mt-4 font-bold text-[#172629]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#566267]">{text}</p></article>)}</div></LegalSection>
    <LegalSection title="Wat je kunt verwachten"><ul className="grid gap-4 sm:grid-cols-2"><li className="flex gap-3"><ShieldCheck className="shrink-0 text-[#bd513c]" size={20} /><span><strong>Een helder profiel:</strong> opdrachtgevers zien relevante informatie en je verificatiestatus.</span></li><li className="flex gap-3"><CalendarCheck2 className="shrink-0 text-[#bd513c]" size={20} /><span><strong>Grip op je planning:</strong> geef beschikbaarheid aan en voorkom onduidelijke afspraken.</span></li><li className="flex gap-3"><WalletCards className="shrink-0 text-[#bd513c]" size={20} /><span><strong>Overzicht over geldzaken:</strong> betalingen en facturen worden centraal bijgehouden.</span></li><li className="flex gap-3"><ArrowRight className="shrink-0 text-[#e76f51]" size={20} /><span><strong>Een eerlijke werkstroom:</strong> reageer zelf, bespreek afspraken en bouw beoordelingen op.</span></li></ul></LegalSection>
    <LegalSection title="Privacy, verificatie en ondersteuning"><p>Je bepaalt welke profielinformatie je deelt. Documenten voor verificatie zijn niet openbaar en worden alleen gebruikt voor controle, veiligheid en wettelijke verplichtingen. Lees de <Link className="font-bold text-[#08705f] underline" href="/privacy">privacyverklaring</Link> en het <Link className="font-bold text-[#08705f] underline" href="/verificatie">verificatiebeleid</Link>.</p><p>Heb je een probleem met een opdracht of inhoud? Gebruik <Link className="font-bold text-[#08705f] underline" href="/melden">Meld een probleem</Link>. Je kunt ook altijd je privacyrechten gebruiken.</p><div className="mt-6 flex flex-wrap gap-3"><Link className="inline-flex items-center gap-2 rounded-lg bg-[#e76f51] px-5 py-3 text-sm font-bold text-white hover:bg-[#cf5f45]" href="/register?role=SECURITY_PROFESSIONAL">Account voor beveiliger <ArrowRight size={17} /></Link><Link className="inline-flex items-center gap-2 rounded-lg border border-[#cfd9d5] px-5 py-3 text-sm font-bold text-[#172629] hover:bg-white" href="/voorwaarden">Bekijk voorwaarden <ArrowRight size={17} /></Link></div></LegalSection>
  </LegalPage>;
}
