import Link from "next/link";
import { ArrowRight, BadgeCheck, MessageSquareText, ShieldCheck } from "lucide-react";
import { LegalPage, LegalSection } from "@/components/legal-page";

const points = [
  ["Beschrijf je behoefte", "Vertel wat je nodig hebt, wanneer de inzet plaatsvindt en welke ervaring belangrijk is."],
  ["Vergelijk professionals", "Bekijk reacties, profielinformatie, beschikbaarheid en verificatiestatus voordat je kiest."],
  ["Houd alles overzichtelijk", "Berichten, planning, afspraken, betalingen en facturen blijven bij elkaar op het platform."],
];

export default function ClientInformationPage() {
  return <LegalPage showDataNotice={false} eyebrow="Voor ondernemers" title="Vind passende beveiliging met overzicht en vertrouwen." introduction="SecurityMatch helpt je om beveiligingsprofessionals te vinden, reacties te vergelijken en de samenwerking professioneel te organiseren. Je houdt zelf de regie over de opdracht.">
    <LegalSection title="Zo werkt het"><div className="grid gap-4 sm:grid-cols-3">{points.map(([title, text], index) => <article key={title} className="border border-[#dce4e1] bg-white p-5"><span className="text-sm font-bold text-[#08705f]">0{index + 1}</span><h3 className="mt-4 font-bold text-[#172629]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#566267]">{text}</p></article>)}</div></LegalSection>
    <LegalSection title="Waarom opdrachtgevers voor SecurityMatch kiezen"><ul className="grid gap-4 sm:grid-cols-2"><li className="flex gap-3"><BadgeCheck className="shrink-0 text-[#08705f]" size={20} /><span><strong>Meer zekerheid:</strong> profielen kunnen worden gecontroleerd en je ziet relevante informatie op één plek.</span></li><li className="flex gap-3"><MessageSquareText className="shrink-0 text-[#08705f]" size={20} /><span><strong>Korte lijnen:</strong> maak afspraken en houd communicatie bij de opdracht.</span></li><li className="flex gap-3"><ShieldCheck className="shrink-0 text-[#08705f]" size={20} /><span><strong>Veilig omgaan met gegevens:</strong> documenten zijn niet openbaar en toegang is beperkt tot bevoegde gebruikers.</span></li><li className="flex gap-3"><ArrowRight className="shrink-0 text-[#e76f51]" size={20} /><span><strong>Ondersteuning:</strong> meldingen, klachten en geschillen kunnen via het platform worden doorgegeven.</span></li></ul></LegalSection>
    <LegalSection title="Privacy en klanttevredenheid"><p>Je gebruikt het platform met duidelijke afspraken. We verzamelen alleen gegevens die nodig zijn voor accountbeheer, matching, communicatie, verificatie en administratie. Bekijk de <Link className="font-bold text-[#08705f] underline" href="/privacy">privacyverklaring</Link> voor meer informatie.</p><p>Na een samenwerking kunnen gebruikers een beoordeling achterlaten. Problemen of ongewenste inhoud kun je melden; SecurityMatch kan dit onderzoeken en passende maatregelen nemen.</p><div className="mt-6 flex flex-wrap gap-3"><Link className="inline-flex items-center gap-2 rounded-lg bg-[#e76f51] px-5 py-3 text-sm font-bold text-white hover:bg-[#cf5f45]" href="/register?role=CLIENT">Account voor ondernemer <ArrowRight size={17} /></Link><Link className="inline-flex items-center gap-2 rounded-lg border border-[#cfd9d5] px-5 py-3 text-sm font-bold text-[#172629] hover:bg-white" href="/voorwaarden">Bekijk voorwaarden <ArrowRight size={17} /></Link></div></LegalSection>
  </LegalPage>;
}
