import Link from "next/link";
import { ArrowRight, BadgeCheck, BriefcaseBusiness, Check, ShieldCheck } from "lucide-react";

const steps = [
  ["Vertel wat je nodig hebt", "Omschrijf de opdracht, locatie, tijden en het type beveiliging."],
  ["Bekijk passende profielen", "Vergelijk ervaring, beschikbaarheid en verificatie voordat je kiest."],
  ["Houd de samenwerking bij", "Berichten, afspraken, betalingen en facturen staan overzichtelijk bij elkaar."],
];

const benefits = ["Een opdracht plaatsen zonder lange omweg", "Reacties rustig naast elkaar vergelijken", "Duidelijke afspraken voor iedereen", "Beoordelingen na afloop van de samenwerking"];

export default function ClientInformationPage() {
  return <main className="overflow-hidden bg-[#f4faf6] text-[#172629]">
    <section className="relative bg-[#08705f] px-5 py-8 text-white sm:px-8 lg:px-10 lg:py-12"><div className="mx-auto max-w-7xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-bold text-[#d8eee7] hover:text-white"><ArrowRight className="rotate-180" size={16} />Terug naar home</Link><div className="grid items-end gap-10 pb-12 pt-16 lg:grid-cols-[1.1fr_0.9fr] lg:pb-20 lg:pt-24"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#b8e1d4]">Voor ondernemers</p><h1 className="mt-5 text-5xl font-bold leading-[1.03] sm:text-6xl">Goede beveiliging begint met overzicht.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-[#e1f3ed]">Van een druk evenement tot vaste objectbeveiliging: vind de professional die past bij jouw opdracht en houd zelf de regie.</p><div className="mt-9 flex flex-wrap gap-3"><Link className="inline-flex min-h-12 items-center gap-2 rounded-lg bg-[#f7baaa] px-5 text-sm font-bold text-[#172629] hover:bg-white" href="/register?role=CLIENT">Ik zoek beveiliging <ArrowRight size={17} /></Link><Link className="inline-flex min-h-12 items-center gap-2 rounded-lg border border-white/40 px-5 text-sm font-bold text-white hover:bg-white/10" href="#zo-werkt-het">Zo werkt het <ArrowRight size={17} /></Link></div></div><div className="relative"><div className="absolute -inset-4 rotate-2 bg-[#f7baaa]/20" /><div className="relative bg-[#f7baaa] p-7 text-[#172629] sm:p-9"><BriefcaseBusiness size={34} /><p className="mt-12 text-3xl font-bold leading-tight">Van vraag naar een duidelijke afspraak.</p><p className="mt-4 text-sm leading-6 text-[#334749]">Alle belangrijke stappen op één plek, zodat jij bezig kunt blijven met je onderneming.</p></div></div></div></div></section>
    <section id="zo-werkt-het" className="px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 border-b border-[#cfe1d9] pb-8 md:flex-row md:items-end"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#08705f]">Zo werkt het</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">In drie stappen geregeld.</h2></div><p className="max-w-md text-sm leading-6 text-[#566267]">Je hoeft niet te verdwalen in losse berichten, spreadsheets en telefoontjes.</p></div><div className="grid gap-5 pt-8 md:grid-cols-3">{steps.map(([title, text], index) => <article key={title} className="border-t-4 border-[#08705f] bg-white p-6"><span className="text-sm font-bold text-[#08705f]">0{index + 1}</span><h3 className="mt-8 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-7 text-[#566267]">{text}</p></article>)}</div></div></section>
    <section className="bg-white px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[0.8fr_1.2fr] lg:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#08705f]">Meer rust in je opdracht</p><h2 className="mt-3 text-3xl font-bold sm:text-4xl">Jij kiest. Het platform houdt overzicht.</h2><p className="mt-5 max-w-lg text-base leading-7 text-[#566267]">SecurityMatch helpt bij het vinden en organiseren van een samenwerking. De keuze en afspraken blijven bij jou.</p><Link className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#08705f] underline underline-offset-4" href="/register?role=CLIENT">Start als ondernemer <ArrowRight size={17} /></Link></div><ul className="grid gap-4 sm:grid-cols-2">{benefits.map((benefit) => <li key={benefit} className="flex items-start gap-3 border-b border-[#dce8e2] pb-4 text-sm font-semibold"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#d8eee7] text-[#08705f]"><Check size={14} strokeWidth={3} /></span>{benefit}</li>)}</ul></div></section>
    <section className="px-5 py-16 sm:px-8 lg:px-10 lg:py-24"><div className="mx-auto max-w-7xl border-l-4 border-[#f7baaa] bg-[#e8f4ef] p-7 sm:p-10"><div className="grid gap-8 md:grid-cols-[auto_1fr] md:items-start"><ShieldCheck className="text-[#08705f]" size={34} /><div><h2 className="text-2xl font-bold">Veilig samenwerken, helder communiceren.</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-[#566267]">Profielinformatie en verificatiestatus zijn inzichtelijk voor de samenwerking. Documenten zijn niet openbaar. We behandelen gegevens volgens onze <Link className="font-bold text-[#08705f] underline" href="/privacy">privacyverklaring</Link>. Een vraag of probleem? <Link className="font-bold text-[#08705f] underline" href="/melden">Meld het bij ons</Link>.</p><div className="mt-6 flex items-center gap-2 text-sm font-bold text-[#08705f]"><BadgeCheck size={18} />Ruimte voor duidelijke afspraken en feedback</div></div></div></div></section>
    <section className="bg-[#172629] px-5 py-16 text-white sm:px-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="text-sm font-bold uppercase tracking-[0.16em] text-[#f7baaa]">Klaar om te beginnen?</p><h2 className="mt-3 text-3xl font-bold">Maak ruimte voor de juiste beveiliging.</h2></div><Link className="inline-flex min-h-12 items-center justify-center gap-2 rounded-lg bg-[#f7baaa] px-5 text-sm font-bold text-[#172629] hover:bg-white" href="/register?role=CLIENT">Account maken <ArrowRight size={17} /></Link></div></section>
  </main>;
}
