import { redirect } from "next/navigation";
import Image from "next/image";
import { auth } from "../../../../../auth";
import { prisma } from "@/lib/prisma";
import { ProfileForm } from "./profile-form";

export default async function SecurityProfilePage() {
  const session = await auth();
  if (!session?.user) redirect("/login");
  if (session.user.role !== "SECURITY_PROFESSIONAL") redirect(`/dashboard/${session.user.role === "ADMIN" ? "admin" : "client"}`);
  const profile = await prisma.securityProfile.findUnique({ where: { userId: session.user.id }, include: { user: { select: { firstName: true, lastName: true, avatarUrl: true, reviewsReceived: { where: { status: "PUBLISHED" }, select: { rating: true, title: true, body: true, createdAt: true }, orderBy: { createdAt: "desc" } } } } } });
  return <main className="min-h-screen bg-slate-100 px-5 py-8 sm:px-8"><div className="mx-auto max-w-4xl"><div className="flex items-center justify-between"><a href="/dashboard/security" className="text-sm font-bold text-slate-600 hover:text-slate-950">← Dashboard</a><span className="text-xl font-bold tracking-[-0.05em] text-slate-950">Security<span className="text-orange-600">Match</span></span></div><div className="mt-10 grid gap-6 lg:grid-cols-[0.72fr_1.28fr]"><aside className="h-fit rounded-2xl bg-slate-950 p-7 text-white"><div className="flex h-20 w-20 items-center justify-center overflow-hidden rounded-full bg-orange-500 text-2xl font-bold">{profile?.user.avatarUrl ? <Image src={profile.user.avatarUrl} alt="Profielfoto" width={80} height={80} unoptimized className="h-full w-full object-cover" /> : (profile?.user.firstName?.[0] ?? "S")}</div><h1 className="mt-6 text-2xl font-bold">{profile?.user.firstName} {profile?.user.lastName}</h1><p className="mt-2 text-sm text-slate-400">Jouw professionele profiel</p>{profile?.verificationStatus === "VERIFIED" && <span className="mt-6 inline-flex rounded-full bg-emerald-400/15 px-3 py-1 text-xs font-bold text-emerald-300">Geverifieerd</span>}<div className="mt-8 space-y-4 border-t border-white/10 pt-6 text-sm"><p><span className="block text-slate-500">Ervaring</span>{profile?.yearsExperience ?? 0} jaar</p><p><span className="block text-slate-500">Werkgebied</span>{profile?.workArea || "Nog niet ingevuld"}</p><p><span className="block text-slate-500">Uurtarief</span>{profile?.hourlyRateCents ? `€ ${(profile.hourlyRateCents / 100).toFixed(2)}` : "Nog niet ingevuld"}</p><p><span className="block text-slate-500">Reviews</span>{profile?.ratingCount ?? 0} beoordelingen</p></div></aside><section className="rounded-2xl bg-white p-6 shadow-sm sm:p-8"><p className="text-xs font-bold uppercase tracking-[0.18em] text-orange-600">Profiel beheren</p><h2 className="mt-3 text-3xl font-bold tracking-[-0.04em] text-slate-950">Laat opdrachtgevers zien wie je bent.</h2><p className="mt-3 text-sm leading-6 text-slate-600">Een compleet profiel helpt bij een betere match. Je verificatiestatus wordt door SecurityMatch beheerd.</p><div className="mt-8"><ProfileForm initialData={{ firstName: profile?.user.firstName ?? "", lastName: profile?.user.lastName ?? "", avatarUrl: profile?.user.avatarUrl ?? "", bio: profile?.bio ?? "", city: profile?.city ?? "", workArea: profile?.workArea ?? "", hourlyRateCents: profile?.hourlyRateCents ?? 0, yearsExperience: profile?.yearsExperience ?? 0, specializations: profile?.specializations ?? [], languages: profile?.languages ?? [], driverLicense: profile?.driverLicense ?? "", ownTransport: profile?.ownTransport ?? false, availability: profile?.availability ?? "" }} /></div></section></div></div></main>;
}
