"use client";

import Link from "next/link";
import { useState } from "react";

type Conversation = { id: string; job: { id: string; title: string } | null; members: { user: { id: string; firstName: string; lastName: string } }[]; messages: { id: string; body: string; senderId: string; readAt: string | null; createdAt: string }[] };

export function MessagesPanel({ currentUserId, initialConversations }: { currentUserId: string; initialConversations: Conversation[] }) {
  const [conversations, setConversations] = useState(initialConversations); const [selectedId, setSelectedId] = useState(initialConversations[0]?.id ?? ""); const [body, setBody] = useState(""); const selected = conversations.find((item) => item.id === selectedId); const other = selected?.members.find((item) => item.user.id !== currentUserId)?.user;
  async function send(event: React.FormEvent) { event.preventDefault(); if (!selected?.job || !other || !body.trim()) return; const response = await fetch("/api/messages", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ recipientId: other.id, jobId: selected.job.id, body }) }); const message = await response.json(); if (response.ok) { setConversations((items) => items.map((item) => item.id === selected.id ? { ...item, messages: [...item.messages, { ...message, createdAt: message.createdAt, readAt: null }] } : item)); setBody(""); } }
  async function markRead(messageId: string) {
    const response = await fetch(`/api/messages?id=${messageId}`, { method: "PATCH" });
    if (response.ok)
      setConversations((items) => items.map((item) => ({
        ...item,
        messages: item.messages.map((message) => message.id === messageId ? { ...message, readAt: new Date().toISOString() } : message),
      })));
  }
  return <main className="min-h-screen bg-slate-100 px-5 py-8 sm:px-8"><div className="mx-auto max-w-6xl"><Link href="/" className="text-xl font-bold tracking-[-0.05em] text-slate-950">Security<span className="text-orange-600">Match</span></Link><h1 className="mt-10 text-3xl font-bold text-slate-950">Berichten</h1><div className="mt-6 grid min-h-[520px] overflow-hidden rounded-xl bg-white shadow-sm md:grid-cols-[280px_1fr]"><aside className="border-r border-slate-100">{conversations.map((item) => { const person = item.members.find((member) => member.user.id !== currentUserId)?.user; const unread = item.messages.filter((message) => message.senderId !== currentUserId && !message.readAt).length; return <button key={item.id} onClick={() => setSelectedId(item.id)} className={`w-full border-b border-slate-100 p-4 text-left ${item.id === selectedId ? "bg-orange-50" : ""}`}><strong className="block text-sm text-slate-900">{person?.firstName} {person?.lastName}</strong><span className="mt-1 block truncate text-xs text-slate-500">{item.job?.title ?? "Opdracht"}</span>{unread > 0 && <span className="mt-2 inline-block rounded-full bg-orange-500 px-2 py-0.5 text-xs font-bold text-white">{unread} ongelezen</span>}</button>; })}{conversations.length === 0 && <p className="p-5 text-sm text-slate-500">Nog geen gesprekken.</p>}</aside><section className="flex flex-col">{selected ? <><header className="border-b border-slate-100 p-5"><h2 className="font-bold text-slate-950">{other?.firstName} {other?.lastName}</h2><p className="text-sm text-slate-500">{selected.job?.title}</p></header><div className="flex-1 space-y-3 overflow-y-auto p-5">{selected.messages.map((message) => <div key={message.id} onClick={() => message.senderId !== currentUserId && !message.readAt && markRead(message.id)} className={`max-w-[80%] rounded-xl p-3 text-sm ${message.senderId === currentUserId ? "ml-auto bg-orange-500 text-white" : "bg-slate-100 text-slate-800"}`}><p>{message.body}</p><time className="mt-2 block text-[11px] opacity-70">{new Date(message.createdAt).toLocaleString("nl-NL")}</time></div>)}</div><form onSubmit={send} className="flex gap-3 border-t border-slate-100 p-4"><input required value={body} onChange={(event) => setBody(event.target.value)} placeholder="Schrijf een bericht" /><button className="rounded-lg bg-orange-500 px-4 text-sm font-bold text-white">Versturen</button></form></> : <p className="p-8 text-slate-500">Selecteer een gesprek.</p>}</section></div></div></main>;
}